# Generated by Django 5.0.1 on 2024-01-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_api', '0005_order_delivered_date_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_DONE', 'Payment Done'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On The Way'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_DONE', 'Payment Done'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order_api.order')),
            ],
        ),
    ]
