# Generated by Django 5.0.1 on 2024-01-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_api', '0006_remove_order_order_status_remove_order_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
