# Generated by Django 5.0.1 on 2024-01-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_api', '0010_alter_logs_order_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
